title: Sparse Tile Mosaic Compiler
description: A compiler for tiled sparsity in Triton.
theme: just-the-docs

url: https://paramathic.github.io/stoicc-docs/

math: mathjax

ga_tracking: G-4R3QLR49DS
ga_tracking_anonymize_ip: true 

callouts:
  note:
    title: Note
    color: blue
